# Generated by Django 5.1.4 on 2025-03-01 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='external_order_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the order in the matching engine', null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='is_buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='order_type',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], default='LIMIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='trading_app.stocktransaction'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Partially_complete', 'Partially Complete'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='trading_app.wallettransaction'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user_id', 'stock', 'is_buy'], name='stock_trans_user_id_8eeeca_idx'),
        ),
    ]
