# Generated by Django 5.1.4 on 2025-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_alter_stock_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
