# Generated by Django 5.1.4 on 2025-03-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_alter_stocktransaction_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='stock_transaction_id',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='stock_transaction',
            field=models.ForeignKey(blank=True, db_column='stock_transaction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='trading_app.stocktransaction'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_stock_transaction', to='trading_app.wallettransaction'),
        ),
    ]
