# Generated by Django 5.1.4 on 2025-03-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_remove_wallettransaction_stock_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_stock_tx', to='trading_app.wallettransaction'),
        ),
    ]
