# Generated by Django 5.1.4 on 2025-03-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_remove_stocktransaction_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, help_text='Trace ID for tracking across services', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='is_buy',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Partially_complete', 'Partially Complete'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='is_debit',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='stocks_symbol_7bc68d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price'], name='stocks_current_1e7687_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user_id', 'is_buy'], name='stock_trans_user_id_78b64c_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['status'], name='stock_trans_status_40d6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user_id', 'status'], name='stock_trans_user_id_7d9f64_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user_id', 'stock', 'status'], name='stock_trans_user_id_3f04bf_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['timestamp'], name='stock_trans_timesta_be69f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['user_id', 'timestamp'], name='stock_trans_user_id_2148f0_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user_id'], name='user_portfo_user_id_a066b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['stock', 'user_id'], name='user_portfo_stock_i_184cca_idx'),
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['quantity'], name='user_portfo_quantit_ec0446_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user_id'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user_id', 'timestamp'], name='wallet_tran_user_id_b32c35_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['stock_transaction'], name='wallet_tran_stock_t_f532ca_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user_id', 'is_debit'], name='wallet_tran_user_id_9b6378_idx'),
        ),
    ]
