# Generated by Django 5.1.4 on 2025-03-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_stocktransaction_trace_id_alter_stock_symbol_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price', 'company_name'], name='price_company_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['order_type', 'status'], name='order_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['price', 'is_buy', 'status'], name='price_buy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['external_order_id', 'status'], name='ext_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user_id', 'amount'], name='user_amount_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['timestamp', 'is_debit'], name='time_debit_idx'),
        ),
    ]
