# Generated by Django 5.1.4 on 2025-02-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
